### ISSUE TITLE
remove unneeded dependencies

### ISSUE THREAD

**Issue by petri** [oddjobz/pymamba#7]
Why is pymamba requiring pymongo? I could not find it being used anywhere in code...?

Are there some other unneeded dependencies? It would be good to remove them.

Thanks.

**Comment by oddjobz** [comment]
Hi Petri, as far as I'm aware there are no unneeded dependencies. The code is dependent on the ObjectId() class that is a part of PyMongo, indeed part of the reason for using this is to be compatible with Python ObjectId's. Although it looks like ObjectId is a part of the BSON library, it's actually a part of PyMongo and doesn't look easy to extricate. I guess I could borrow the ObjectId code from PyMongo, but then compatibility isn't guaranteed .. is the size of the PyMongo code a problem?

**Comment by petri** [comment]
No, the size is not really a problem. If the goal is to be compatible bson objectids, are you aware of https://pypi.python.org/pypi/bson ? Would that accomplish the same thing?

For what it is worth, I also took a look at the PyMongo bson stuff and looks like extracting the ObjectId stuff is actually easy. It is all mostly in one module, Python only (no C extensions involved).

**Comment by oddjobz** [comment]
Hi, I believe the mongo ObjectId code actually uses the "bson" module, so yes. It's not technically difficult to copy the ObjectId code, the issue was including someone else's code in the repo, which is covered by a different license, then having to remember to check back to the PyMongo implementation at regular intervals to see if they have updated or changed the code in any way. Whereas I appreciate it hasn't changed much recently, I'm wondering (given the overhead) what the gain is in doing this? It's a little additional disk storage, but the import statement will "only" import the ObjectId code, so there's no run-time overhead ... (?)

**Comment by petri** [comment]
Ah, looks like [ObjectId is not yet supported](https://github.com/py-bson/bson/issues/39) by the standalone bson package... I added a suggestion about copying the PyMongo ObjectId code...

**Comment by oddjobz** [comment]
Mmm, if ObjectId() was included in the BSON module, that would be cool .. :)

**Comment by petri** [comment]
I guess the question is, what is the point of using the bson ObjectIds? Is it to maintain compatibility with PyMongo?

In any case, bson (including bson ObjectId) has  [its own specification](http://bsonspec.org/spec.html), so I don't think you have to worry about checking the PyMongo implementation.

**Comment by petri** [comment]
@oddjobz, I submitted a PR to the bson package doing exactly what I proposed here (copied over the implementation from PyMongo).

**Comment by petri** [comment]
@oddjobz ObjectId() is now included in the BSON module. The implementation is a straight copy from PyMongo, so it is safe to require BSON instead of PyMongo :)

**Comment by oddjobz** [comment]
Sounds good, I'm currently working on a very large change-set to include replication, I'll look to include the change as part of the new code :)
